### ISSUE TITLE
Move Core Rules Assistant into the monorepo

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistant-core-rules#125]
### QA

1. Git clone `git@github.com:sketch-hq/sketch-assistants.git`
1. Checkout the PR branch `git checkout feature/add-core-rules`
1. In the repo root run `yarn`
1. Still in the repo root run `yarn build`

For the three assistants `tidy`, `reuse-suggestions` and `naming-conventions` ensure that they can still be packaged and added to Sketch locally, and they generate the expected violations.

E.g.

```sh
cd assistants/tidy
yarn package-tarball
# Then "Add from Disk" in Sketch Experimental
```

**Comment by smithzoo** [comment]
Testing `6c7fd70d` with current Experimental 67 (97808).

1. Git clone `git@github.com:sketch-hq/sketch-assistants.git`
2. Checkout the PR branch `git checkout feature/add-core-rules`
3. In the repo root run `yarn`
4. Still in the repo root run `yarn build`
5. `cd` assistants/reuse-suggestions
6. `yarn package-tarball`
7. Install `sketch-hq-sketch-reuse-suggestions-assistant-v5.0.0-next.9` via disk in Experimental
8. Add a shape and duplicate is a few times
9. Add a text layer and duplicate is a few times
10. View the Assistant results

![image](https://user-images.githubusercontent.com/4378001/81593243-2b0a7980-938d-11ea-9baa-489f896ce39d.png)

**Comment by jedrichards** [comment]
@smithzoo This is ready for another test using same steps as above 🙇.
